# spring.application.name=magulaplan
#_
#_
#_
# spring.jpa.generate-ddl=true
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

spring.application.name=magulaplan
spring.profiles.active=local

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true